### ISSUE TITLE
seru updates 

### ISSUE THREAD

**Issue by indykish** [megamsys/chef-repo#33]
- seru to mask its command
- seru to be loaded internally in the image

**Comment by thomasalrin** [comment]
'execute' template has a property called 'sensitive' to hide execution log.

**Comment by thomasalrin** [comment]
issue fixed. so close this issue

**Comment by thomasalrin** [comment]
5 Recipe: megam_dns::route53
103.56.92.35   * remote_file[/home/megam/bin/seru.tar.gz] action create
103.56.92.35     - create new file /home/megam/bin/seru.tar.gz
103.56.92.35     - update content in file /home/megam/bin/seru.tar.gz from none to 7d6349
103.56.92.35     (new content is binary, diff output suppressed)
103.56.92.35     - change owner from '' to 'megam'
103.56.92.35     - change group from '' to 'megam'
103.56.92.35   * bash[Unzip seru] action run
103.56.92.35     - execute "bash"  "/tmp/chef-script20150814-20941-fvkwdl"
103.56.92.35   * execute[route53 create record ] action run
103.56.92.35     - execute sensitive resource
