### ISSUE TITLE
Gulp should be installed and be up after a certain point is reached.

### ISSUE THREAD

**Issue by indykish** [megamsys/chef-repo#35]

**Comment by indykish** [comment]
Better yet, it would be great if you can do something like
1. Install gulp at the start  (since this is needed in all runs, your image should have it inside it).
No need to download and install always.
2. Start gulp when the run `exits`. An exit can be a failure or success. 

This will make sure no matter what, gulp will run.

**Comment by indykish** [comment]
success or a failure of a cookbook run shall have gulpd running.

**Comment by indykish** [comment]
@thomasalrin  If this is done, then close it.

**Comment by thomasalrin** [comment]
@indykish We have installed gulpd in our images itself. It will automatically start gulpd, when an instance is boot from our images.
