### ISSUE TITLE
Changes in cookbook - app+bind - petclinic + postgres

### ISSUE THREAD

**Issue by morpheyesh** [megamsys/chef-repo#36]
1. Fix password and role issue in postgres
2. Add  'listen_address=<appIP> ' and 'tcpip_socket = true'

**Comment by indykish** [comment]
@thomasalrin  Is this complete ?

**Comment by thomasalrin** [comment]
@indykish It is not completed yet. We need to test it.

**Comment by indykish** [comment]
This isn't valid i think or a fix has been applied ? @thomasalrin  fya.
