### ISSUE TITLE
Version upgrade of chef cookbooks

### ISSUE THREAD

**Issue by indykish** [megamsys/chef-repo#46]
Keeping cookbooks perpertually upgradable is good, but we need to baseline and release incremental fixes.

What is our design and how will this approach work with our agent gulpd.?

**Comment by thomasalrin** [comment]
For temporary fix, `gulpd` checks for `chef-repo` directory at `/var/lib/megam`, it it is present, gulpd wont clone chef-repo. If it is doesn't present, gulpd wil clone chef-repo
