### ISSUE TITLE
chef-solo error on megam_rabbitmq cookbook

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/chef-repo#74]
================================================================================
Recipe Compile Error in /var/lib/megam/gulp/chef-repo/cookbooks/megam_run/recipes/default.rb
================================================================================

NoMethodError
-------------
Undefined node attribute or method `push' on `node'. To set an attribute, use `push=value' instead.

Cookbook Trace:
---------------
 /var/lib/megam/gulp/chef-repo/cookbooks/megam_rabbitmq/recipes/default.rb:24:in `from_file'
 /var/lib/megam/gulp/chef-repo/cookbooks/megam_route/definitions/route.rb:47:in `block in from_file'
 /var/lib/megam/gulp/chef-repo/cookbooks/megam_route/recipes/default.rb:9:in `from_file'
 /var/lib/megam/gulp/chef-repo/cookbooks/megam_run/recipes/default.rb:39:in `from_file'

Relevant File Content:
----------------------
/var/lib/megam/gulp/chef-repo/cookbooks/megam_rabbitmq/recipes/default.rb:

17:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
18:  # See the License for the specific language governing permissions and
19:  # limitations under the License.
20:  #
21:  
22:  rsyslog_inputs=[]
23:  rsyslog_inputs = node.default['rsyslog']['logs']
24>> rsyslog_inputs.push("/var/log/rabbitmq/rabbit@#{`hostname`}.log", "/var/log/megam/megamgulpd/megamgulpd.log")
25:  node.override['rsyslog']['logs']= rsyslog_inputs
26:  
27:  node.set['heka']['logs']["#{node['megam']['deps']['component']['name']}"] = ["/var/log/rabbitmq/rabbit@#{`hostname`}.log", "/var/log/megam/megamgulpd/megamgulpd.log"]
28:  
29:  dir = "rabbitmq"
30:  
31:  include_recipe "erlang"
32:  
33:  #include_recipe "megam_ganglia::rabbit"

Running handlers:
[2016-01-22T14:04:32+01:00] ERROR: Running exception handlers
Running handlers complete
[2016-01-22T14:04:32+01:00] ERROR: Exception handlers complete
[2016-01-22T14:04:32+01:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 2.730853115 seconds
[2016-01-22T14:04:32+01:00] ERROR: Undefined node attribute or method `push' on `node'. To set an attribute, use `push=value' instead.
[2016-01-22T14:04:32+01:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by thomasalrin** [comment]
@vijaykanthm28 test it with new chef-repo
