### ISSUE TITLE
couchdb cookbook execting error while run  make install 

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/chef-repo#84]
execute[install couchdb] ran successfully\n\n     
execute wget http://ftp.fau.de/apache/couchdb/source/1.6.1/apache-couchdb-1.6.1.tar.gz\x1b[0m  * execute[tar xvzf apache-couchdb-*] action run[2016-03-18T13:12:09+00:00]
 INFO: Processing execute[tar xvzf apache-couchdb-*] action run (megam_couchdb::default line 35)\n[2016-03-18T13:12:09+00:00] 
INFO: execute[tar xvzf apache-couchdb-*] ran successfully\n\n     execute tar xvzf apache-couchdb-*\x1b[0m  * bash[make] action run[2016-03-18T13:12:09+00:00] 
INFO: Processing bash[make] action run (megam_couchdb::default line 37)\n\n       
============================================================================= 
\x1b[31mError executing action `run` on resource 'bash[make]'   =============================================================================   

Mixlib::ShellOut::ShellCommandFailed   ------------------------------------   Expected process to exit with [0], but received '2'    ---- Begin output of \"bash\"  \"/tmp/chef-script20160318-1335-16jbd88\" ----    STDOUT: checking for a BSD-compatible install... /usr/bin/install -c    checking whether build environment is sane... yes    
checking for a thread-safe mkdir -p... /bin/mkdir -p    
checking for gawk... gawk    checking whether make sets $(MAKE)... yes    checking how to create a ustar tar archive... gnutar    checking for style of include used by make... GNU    checking for gcc... gcc    checking whether the C compiler works... yes    checking for C compiler default output file name... a.out    checking for suffix of executables...     checking whether we are cross compiling... no    checking for suffix of object files... o    checking whether we are using the GNU C compiler... yes    checking whether gcc accepts -g... yes    checking for gcc option to accept Ision compatibility... detected Erlang version: 0.0.0...    STDERR: ./configure: line 18138: fg: no job control    configure: error: The installed Erlang version must be >= R14B (erts-5.8.1) and =< 17 (erts-6.0) major_version does not match    make: *** No rule to make target `install'.  Stop.    ---- End output of \"bash\"  \"/tmp/chef-script20160318-1335-16jbd88\" ----    Ran \"bash\"  \"/tmp/chef-script20160318-1335-16jbd88\" returned 2       Resource Declaration:   ---------------------  
 # In /var/lib/megam/gulp/chef-repo/cookbooks/megam_couchdb/recipes/default.rb         
37: bash 'make' do     
38:   code <<-EOH     
39:     cd apache-couchdb-*     
40:       ./configure && make     
41:      make install     
42:   EOH     
43: end     
44:         Compiled Resource:   ------------------  
 # Declared in /var/lib/megam/gulp/chef-repo/cookbooks/megam_couchdb/recipes/default.rb:37:in `from_file'        bash(\"make\") do      action \"run\"      retries 0      retry_delay 2      default_guard_interpreter :default      command \"make\"      backup 5      returns 0     
 code \"    cd apache-couchdb-*\\n 
     ./configure && make\\n     
make install\\n\"     
 interpreter \"bash\"      
declared_type :bash      
cookbook_name :megam_couchdb      recipe_name \"default\"    end    [2016-03-18T13:12:21+00:00] INFO: Running queued delayed notifications before re-raising exception\nRunning handlers:\x1b[0m\n[2016-03-18T13:12:21+00:00] ERROR: Running exception handlers\nRunning handlers complete[2016-03-18T13:12:21+00:00] ERROR: Exception handlers complete\n[2016-03-18T13:12:21+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out\nChef Client failed. 14 resources updated in 772.983609777 seconds\x1b[0m\n[2016-03-18T13:12:21+00:00] ERROR: bash[make] (megam_couchdb::default line 
37) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'\n---- Begin output of 
\"bash\"  \"/tmp/chef-script20160318-1335-16jbd88\" ----\nSTDOUT: checking for a BSD-compatible install... /usr/bin/install -c\nchecking whether build environment is sane... yes\nchecking for a thread-safe mkdir -p... /bin/mkdir -p\nchecking for gawk... gawk\nchecking whether make sets $(MAKE)... yes\nchecking how to create a ustar tar archive... gnutar\nchecking for style of include used by make... GNU\nchecking -prototypes -Wwrite-strings    \nchecking ICU_CXXFLAGS... -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wall -W -Wall -pedantic -Wpointer-arith -Wwrite-strings -Wno-long-long --std=c++0x    \nchecking ICU_LIBS... -Wl,-Bsymbolic-functions -Wl,-z,relro  -ldl -lm   -L/usr/lib/x86_64-linux-gnu -licui18n -licuuc -licudata  -ldl -lm   \nchecking for curl-config... /usr/bin/curl-config\nchecking for curl (7.35.0) >= 7.18.0... yes\nchecking Erlang version compatibility... detected Erlang version: 0.0.0...\nSTDERR: ./configure: line 18138: fg: no job control\nconfigure: error: The installed Erlang version must be >= R14B (erts-5.8.1) and =< 17 (erts-6.0) major_version does not match\nmake: *** No rule to make target `install'.  Stop.\n---- End output of \"bash\"  \"/tmp/chef-script20160318-1335-16jbd88\" ----\nRan \"bash\"  \"/tmp/chef-script20160318-1335-16jbd88\" returned 2\n[2016-03-18T13:12:21+00:00] 

FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)\n  chefsolo run ended failed.\nexit status 1" 
time="2016-03-18T13:12:21Z" level=error msg="Unable to stateup box : exit status 1" 
time="2016-03-18T13:12:21Z" level=debug msg="contrasting.megambox.com_log:{18 Mar 16 13:12 UTC exit status 1 gulp overcompensation COM7873979593084011110}"

**Comment by indykish** [comment]
@vijaykanthm28  can you close this , this is fixed by @vinomca-megam   ?

**Comment by vijaykanthm28** [comment]
issue  fixed by commit #92
